### ISSUE TITLE
Creating package fails but running on DLL passes?

### ISSUE THREAD

**Issue by OnamChilwan** [nunit/nunit.org#37]
Hello, I am experiencing a bizarre issue when running unit tests via the GUI. When I navigate to the DLL and run tests this works fine however when I generate an _nunit project_ and run it, I get failing tests. See below for replication steps.

1. Downloaded version 2.6.4 of the nUnit.
2. Opened a Unit Test DLL and run the tests via the GUI.
3. All these tests pass.
4. File > Save as a "nunit package".
5. Open the project and run.

I get a different output as in tests start failing. Seems as though it's referring to a config section which its trying to get a hold of but hasn't packaged this correctly? I am speculating but would appreciate some assistance as to why this is happening and what the difference is between the two.

**Comment by CharliePoole** [comment]
NOTE: This repository is for the NUnit.org website. Issues against NUnit 3.0 should be filed in the nunit (not nunit.org) repository. Questions about NUnit 2.6.4 or higher are best asked on our nunit-discuss forum on google. I'll try to answer your question here, however.

When you are running a dll, NUnit 2.6.4 looks for a config file named xxxx.dll.config. When you use an nunit project (not package - we use that word in 3.0 for something else) it looks for xxxx.config. See the docs under "configuration files".
