### ISSUE TITLE
Update/Remove VS adapters on download page

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit.org#54]
Noticed doing #53 that the adapter links on the http://nunit.org/index.php?p=download are a few versions behind.

I haven't 'just fixed them' - as I wasn't sure if people would prefer them to be removed instead, if keeping them up-to-date is becoming an extra cost. @OsirisTerje @CharliePoole?

The other alternative of course, is we take the version numbers/release dates off this page, and just have it point to the latest version.

**Comment by CharliePoole** [comment]
@ChrisMaddock Not sure why we might want to remove the adapters...

I took on the task of re-organizing the web pages but forgot to write an issue for it. I'm still used to just working interactively on the site. Anyway, I'll create the issue. 😄

**Comment by CharliePoole** [comment]
BTW the links being out of date is a result of both me and Terje forgetting to do it when we created releases. At least I'm pretty sure the release procedures say we should update the web site.

**Comment by rprouse** [comment]
I have an issue on the new site to update the release. We can also remove the link, but I am going to close here since I expect the new site to be up within the next few days or at least weeks 😄
