### ISSUE TITLE
Revise web site organization to reflect multiple products

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit.org#55]
The site was started when NUnit was just NUnit. When we added the VS adapter, we had two products and that didn't seem like enough to add a Products menu. Now (suddenly?) we have a bunch of things so it's past due.

My general idea is that there will be a top-level product menu with all the info (docs, downloads, etc.) for a single product on a page.

I view this as content reorganization. Any changes to the appearance can come separately, later.

**Comment by ChrisMaddock** [comment]
I think it would be great to have everything on the website! (Tagged appropriately as: 'development' etc, of course. 😉)

A suggestion, if this area is being redone: Can we not show versions/dates, so it's one less place to keep up-to-date? We currently store all versions in GitHub releases. Could the website just link to GitHub? We could continue to update the 'recent news' for new releases.

**Comment by CharliePoole** [comment]
@ChrisMaddock I guess my thinking is that if you have a website, you want to keep it up to date. Knowing when the last release of anything came out seems like a common user desire. I'm pretty sure, once we finalize the website (format, location, etc.) we can figure out ways to make it easier. For example, we can automate or we can have some volunteer who is the webmaster and does all that stuff. 

To be clear, I'd be ready to make a decision on this unilaterally if I were hanging around, but I'm not. And the group that is succeeding me is not yet formed so as to make the decision in a formal way. I should really stop programming and get on with that, but what can I say... I'm a programmer. 😄

**Comment by CharliePoole** [comment]
Taking my name off this. My role will be to figure out a plan for transitioning the website to the core team or to a webmaster that they designate. Any reorganization of content should happen on the new website.

**Comment by jnm2** [comment]
Xamarin's current templates for Android unit tests have a bootstrapper application that says `for NUnitLite, see http://nunitlite.org`. That gives a 404. Did it used to redirect?

**Comment by CharliePoole** [comment]
It's a domain name I gave up over a year ago, with info and docs for the old nunitlite 1.0, which is what they use. I was already planning to expose it as nunitlite.nunitsoftware.org and add a note that it's a whole different thing from nunitlite as now provided by NUnit.

Where would I file an issue when I have a new URL up?

**Comment by ChrisMaddock** [comment]
Not sure if you intentionally or accidentally closed this, @CharliePoole - but I think the original issue is still to do. 🙂

**Comment by CharliePoole** [comment]
Probably means something else I intended to close isn't. 😕

**Comment by rprouse** [comment]
I am not sure if this is the right repo for the issue, but https://github.com/xamarin/Touch.Unit

**Comment by jnm2** [comment]
@rprouse Interesting...

**Comment by CharliePoole** [comment]
I filed an issue on spouliot/Touch.Unit, from which the xamarin repo is forked. FYI, the docs for the old nunitlite are at nunitsoftware.com/nunitlite.

**Comment by rprouse** [comment]
That issue may go ignored. There hasn't been a commit in 4 years and I reached out to the Xamarin people to try to work with them in moving to NUnit 3 and I couldn't get a response despite chatting with Miguel and Nat. I don't think anyone is responsible for it anymore.

**Comment by jnm2** [comment]
They still ship the templates in the product though, so someone has to be responsible for those, right?

**Comment by rprouse** [comment]
> They still ship the templates in the product though, so someone has to be responsible for those, right?

Probably, we just need to find them 😄

**Comment by CharliePoole** [comment]
I believe I found him. I gave him an issue. Him == Sebastien.

In case someone has not seen it before, it's not uncommon in the linux world for the production repo to be a fork of somebody's personal repo, rather than the other way around.

**Comment by jnm2** [comment]
> In case someone has not seen it before, it's not uncommon in the linux world for the production repo to be a fork of somebody's personal repo, rather than the other way around.

Why yes, that did grab my attention. :smile:

**Comment by rprouse** [comment]
Issue moved to [nunit/nunit.github.io #12](https://github.com/nunit/nunit.github.io/issues/12) via [**ZenHub**](https://www.zenhub.com/)
